/** @type {import('@kellnerd/userscript-bundler').EnhancedUserscriptMetadata} */
const metadata = {
	name: 'MusicBrainz: Voice actor credits (Eichi76 dev version)',
	author: 'Eichi76',
	description: 'Parses voice actor credits from text or all artists involved in a audio drama production from a JSON string and automates the process of creating release or recording relationships for them. Also imports credits from Discogs.',
	features: [
		'[DEV] Simplifies the addition of contributor relationships to a audio drama release by inserting a JSON string generated by other scripts into a text field available in the relationship editor.',
		'Simplifies the addition of “spoken vocals” relationships by providing a pre-filled dialogue in the relationship editor.',
		'Parses a list of voice actor credits from text and remembers name to MBID mappings.',
		'Adds relationships to selected recordings, falls back to release relationships (if no recordings are selected).',
		'Imports voice actor credits from linked Discogs release pages.',
		'Automatically matches artists whose Discogs pages are linked to MB (unlinked artists can be selected from the already opened inline search).',
		'Allows seeding of the credit input (`credits`) and the edit note (`edit-note`) via custom query parameters, which are encoded into the hash of the URL (*Example*: `/edit-relationships#credits=Narrator+-+John+Doe&edit-note=Seeding+example`).',
	],
	grant: [
		'GM.getValue',
		'GM.setValue',
	],
	match: '*://*.musicbrainz.org/release/*/edit-relationships',
	'run-at': 'document-idle',
};

export default metadata;
